#!/usr/bin/env bash
# K3 (bd-17c65.11.3) — Build docs/degraded_codes.md from the J6
# (bd-17c65.10.6) failure-mode fixture catalog.
#
# The generated file is the canonical agent-facing reference for every
# `degraded[]` code that can appear in an `ee` response. One section
# per code with: severity, surfaces, introduced-by bead, trigger
# description + setup + invocation, expected emission snippet, repair
# hint, related taxonomy classification when known.
#
# This script is idempotent — running it twice against the same
# fixture set produces a byte-identical doc (sections sorted
# alphabetically by code, no embedded timestamps in the body except
# the header's generated-at line which is intentionally floored to
# the date so re-runs on the same day are no-ops at the file-content
# level).
#
# Wired into the K3 CI gate via tests/degraded_codes_doc_coverage.rs
# which walks the same fixture set and asserts every code appears
# as a section heading in the doc.
#
# Usage:
#   scripts/build_degraded_codes_doc.sh
#
# Reads:
#   tests/fixtures/failure_modes/*.json
#   docs/degraded_code_taxonomy.md   (optional; pulls classification when present)
#
# Writes:
#   docs/degraded_codes.md  (atomic — staged to a tmp path then mv'd)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
FIXTURES_DIR="$REPO_ROOT/tests/fixtures/failure_modes"
OUTPUT="$REPO_ROOT/docs/degraded_codes.md"
TAXONOMY="$REPO_ROOT/docs/degraded_code_taxonomy.md"

if ! command -v jq >/dev/null 2>&1; then
    echo "build_degraded_codes_doc.sh: jq is required" >&2
    exit 2
fi

if [ ! -d "$FIXTURES_DIR" ]; then
    echo "build_degraded_codes_doc.sh: fixtures dir not found: $FIXTURES_DIR" >&2
    exit 3
fi

# Collect every fixture path sorted alphabetically; this is the
# deterministic source-of-truth ordering for the generated catalog.
FIXTURES=()
while IFS= read -r f; do
    FIXTURES+=("$f")
done < <(find "$FIXTURES_DIR" -maxdepth 1 -type f -name '*.json' | LC_ALL=C sort)

if [ "${#FIXTURES[@]}" -eq 0 ]; then
    echo "build_degraded_codes_doc.sh: no fixtures found under $FIXTURES_DIR" >&2
    exit 4
fi

STAGE_OUTPUT="$(mktemp "${OUTPUT}.XXXXXX")"
trap 'rm -f "$STAGE_OUTPUT"' EXIT

# Build the file body. Header documents auto-generation contract;
# operators reading the doc see it cannot be hand-edited without
# being overwritten on the next regen.
{
    cat <<'HEADER'
# Degraded codes catalog

> **AUTO-GENERATED.** Do not edit by hand. This file is regenerated
> from `tests/fixtures/failure_modes/*.json` (the J6 catalog,
> bd-17c65.10.6) by `scripts/build_degraded_codes_doc.sh` (K3,
> bd-17c65.11.3). The CI gate
> `tests/degraded_codes_doc_coverage.rs` fails when a fixture lacks
> a matching section in this file, or when this file has an orphan
> section without a fixture.
>
> **To regenerate:**
> ```bash
> ./scripts/build_degraded_codes_doc.sh
> ```
>
> **To add a code:** drop a fixture under
> `tests/fixtures/failure_modes/<code>.json` matching the
> `ee.failure_mode_fixture.v1` schema, then re-run the script.
>
> **Companion docs:**
> - [`docs/degraded_code_taxonomy.md`](./degraded_code_taxonomy.md) —
>   classification (build_time / response_time / mixed) per the
>   bd-fptj3 taxonomy.
> - [`docs/migration_v0_1_to_v0_2.md`](./migration_v0_1_to_v0_2.md) —
>   the wire-contract delta the v0.2 release introduced; code
>   surfaces refer back to this catalog by code name.

---

## How agents consume this catalog

When an `ee` command returns a response with non-empty `data.degraded[]`,
each entry's `code` field matches one of the section headings below.
The agent should:

1. Look up the section by code.
2. Read **Surface** to confirm the code can fire on the command in question.
3. Read **Severity** to decide whether to retry / warn / abort.
4. If the entry includes `repair` or `recovery[]`, run those first.
5. The **Trigger** section explains when the code fires so an agent
   can avoid the failure mode on subsequent calls.

Per bd-17c65.5.2 (E2), `degraded[]` only emits per-response codes by
default — codes whose category is `affects_this_response`. Build-time
feature gaps and workspace-state codes appear here for reference but
are filtered out of the default per-response array; pass
`--include-non-affecting-degradations` to surface every category.

---

HEADER

    # Total counter line so a reader sees catalog size at a glance.
    echo ""
    echo "## Catalog summary"
    echo ""
    echo "- **Fixtures indexed:** $(printf '%s\n' "${FIXTURES[@]}" | wc -l | tr -d ' ')"
    echo "- **Generated by:** \`scripts/build_degraded_codes_doc.sh\` (K3 / bd-17c65.11.3)"
    if [ -f "$TAXONOMY" ]; then
        echo "- **Taxonomy cross-reference:** [\`degraded_code_taxonomy.md\`](./degraded_code_taxonomy.md)"
    fi
    echo ""
    echo "---"
    echo ""

    # One section per fixture, sorted alphabetically by code.
    for fixture in "${FIXTURES[@]}"; do
        code="$(jq -r '.code // empty' "$fixture")"
        if [ -z "$code" ]; then
            echo "build_degraded_codes_doc.sh: fixture $fixture missing .code" >&2
            exit 5
        fi
        severity="$(jq -r '.severity // "unspecified"' "$fixture")"
        surfaces="$(jq -r '(.surfaces // []) | join(", ")' "$fixture")"
        bead="$(jq -r '.introduced_by.bead // "(unknown)"' "$fixture")"
        epic="$(jq -r '.introduced_by.epic_letter // ""' "$fixture")"
        trigger_desc="$(jq -r '.trigger.description // "(no description provided)"' "$fixture")"
        invocation="$(jq -r '.trigger.invocation // ""' "$fixture")"
        repair_present="$(jq -r '.repair_present // false' "$fixture")"
        repair_contains="$(jq -r '.expected_emission.repair_contains // ""' "$fixture")"
        message_contains="$(jq -r '(.expected_emission.message_contains // []) | join(" ... ")' "$fixture")"

        echo "## \`$code\`"
        echo ""
        echo "**Severity:** $severity"
        if [ -n "$surfaces" ]; then
            echo ""
            echo "**Surfaces:** $surfaces"
        fi
        if [ "$bead" != "(unknown)" ]; then
            if [ -n "$epic" ]; then
                echo ""
                echo "**Introduced by:** $bead (epic $epic)"
            else
                echo ""
                echo "**Introduced by:** $bead"
            fi
        fi
        echo ""
        echo "**Trigger.** $trigger_desc"

        # Setup commands (optional)
        setup_count="$(jq '(.trigger.setup_commands // []) | length' "$fixture")"
        if [ "$setup_count" -gt 0 ]; then
            echo ""
            echo "**Setup.**"
            echo ""
            echo '```bash'
            jq -r '.trigger.setup_commands[]' "$fixture"
            echo '```'
        fi

        if [ -n "$invocation" ] && [ "$invocation" != "null" ]; then
            echo ""
            echo "**Invocation.**"
            echo ""
            echo '```bash'
            echo "$invocation"
            echo '```'
        fi

        echo ""
        echo "**Expected emission.** Message contains: \`$message_contains\`"
        if [ "$repair_present" = "true" ] && [ -n "$repair_contains" ] && [ "$repair_contains" != "null" ]; then
            echo ""
            echo "**Repair hint.** \`$repair_contains\`"
        elif [ "$repair_present" = "true" ]; then
            echo ""
            echo "**Repair hint.** Present in fixture; see the response payload's \`error.repair\` field at runtime."
        else
            echo ""
            echo "**Repair hint.** Not provided — this code is informational; no operator action is required."
        fi

        echo ""
        echo "**Fixture.** [\`tests/fixtures/failure_modes/$(basename "$fixture")\`](../tests/fixtures/failure_modes/$(basename "$fixture"))"
        echo ""
        echo "---"
        echo ""
    done

    cat <<'FOOTER'
## Reporting drift

If a section here does not match the runtime emission you observe,
the gap is one of:

1. **Fixture stale** — the fixture in `tests/fixtures/failure_modes/`
   no longer matches the implementation. Update the fixture, re-run
   `./scripts/build_degraded_codes_doc.sh`.
2. **Implementation stale** — the code emits something the fixture
   asserted away. Update the implementation OR the fixture's
   `expected_emission` block; the J6 catalog gate
   (`tests/contracts/failure_mode_fixtures.rs`) tracks this.
3. **Doc stale** — this file fell out of sync because the regen
   script wasn't run. The CI gate
   (`tests/degraded_codes_doc_coverage.rs`) catches this.

For new degraded codes, follow the J6 fixture-authoring workflow in
`tests/fixtures/failure_modes/` (see any existing fixture as a
template), then regenerate.
FOOTER
} > "$STAGE_OUTPUT"

# Atomically replace the output file so a partial run doesn't leave
# half a doc behind.
mv "$STAGE_OUTPUT" "$OUTPUT"
trap - EXIT

echo "build_degraded_codes_doc.sh: wrote $OUTPUT ($(wc -l < "$OUTPUT" | tr -d ' ') lines, $(printf '%s\n' "${FIXTURES[@]}" | wc -l | tr -d ' ') fixtures indexed)" >&2
